"""Add role column to Admin

Revision ID: 78714a423c4d
Revises: 
Create Date: 2025-10-22 23:18:46.648705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78714a423c4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
